# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch # to protect specific branches from direct checkins.
        args: [--branch, master]
      - id: pretty-format-json
        args: [--autofix]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - name: black formatter
        id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - name: isort
        id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.4
    hooks:
      - id: pylint
        args: ["--rcfile=pylintrc"]
