services:
  otel-collector:
    container_name: mlops-otel-collector
    image: otel/opentelemetry-collector-contrib:0.111.0
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    volumes:
      - ./docker/otel-collector/config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - mlops-network

  prometheus:
    container_name: mlops-prometheus
    env_file:
      - .env
    image: prom/prometheus:v2.54.1
    volumes:
      - ./docker/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - mlops-network

  grafana:
    container_name: mlops-grafana
    labels:
      prometheus-scrape.enabled: "false"
      service: "grafana"
    env_file:
      - .env
    image: grafana/grafana-oss:11.2.2
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - mlops-network

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: mlops-jaeger
    ports:
      - "16686:16686"
    networks:
      - mlops-network

volumes:
  grafana-data: {}
  prometheus-data: {}

networks:
  mlops-network:
