services:
  workspace:
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: gpu_image
    image: getty708/deepstream-sandbox:7.0
    working_dir: /workspace/triton-sandbox/deepstream/concurrent_model_exec
    command: /bin/bash
    tty: true
    volumes:
      - ../../:/workspace/triton-sandbox
    environment:
      PYTHONPATH: /workspace/triton-sandbox
      TF_ENABLE_ONEDNN_OPTS: 0
      USE_NEW_NVSTREAMMUX: yes
    shm_size: 32g
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
