{
 "title": "ML Pipeline Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipelineName",
    "query": {
     "query": "label_values(otel_traces_span_metrics_duration_milliseconds_sum,service_name)"
    }
   },
   {
    "name": "model_1",
    "query": {
     "query": "label_values(otel_traces_span_metrics_duration_milliseconds_sum,span_name)"
    }
   },
   {
    "name": "model_2",
    "query": {
     "query": "label_values(otel_traces_span_metrics_duration_milliseconds_sum,span_name)"
    }
   },
   {
    "name": "model_3",
    "query": {
     "query": "label_values(otel_traces_span_metrics_duration_milliseconds_sum,span_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ML Pipeline Overserbability" } },
  { "title": "Pipeline Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pipeline Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"pipeline\", span_name=\"process_single_frame\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"pipeline\", span_name=\"process_single_frame\"}",
     "legendFormat": "{{service_name}}-{{span_name}}"
    }
   ]
  },
  {
   "title": "Model Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"$pipelineName\", span_name=\"$model_1\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"$pipelineName\", span_name=\"$model_1\"}",
     "legendFormat": "{{span_name}}"
    },
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"$pipelineName\", span_name=\"$model_2\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"$pipelineName\", span_name=\"$model_2\"}",
     "legendFormat": "{{span_name}}"
    },
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"$pipelineName\", span_name=\"$model_3\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"$pipelineName\", span_name=\"$model_3\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "People Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(otel_detected_people_count_total[$__rate_interval])",
     "legendFormat": "$pipelineName"
    }
   ]
  },
  { "title": "Model Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Model Latency ($model_1)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"$pipelineName\", span_name=\"$model_1\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"$pipelineName\", span_name=\"$model_1\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Model Latency ($model_2)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"$pipelineName\", span_name=\"$model_2\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"$pipelineName\", span_name=\"$model_2\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Model Latency ($model_3)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "otel_traces_span_metrics_duration_milliseconds_sum{service_name=\"$pipelineName\", span_name=\"$model_3\"} / otel_traces_span_metrics_duration_milliseconds_count{service_name=\"$pipelineName\", span_name=\"$model_3\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  }
 ]
}