{
 "title": "ML Pipeline Observability",
 "tags": [
  "LLM",
  "VectorDB",
  "GenAI",
  "GPU"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "traceDatasource", "label": "Trace Datasource", "query": "tempo" },
   { "name": "metricsDatasource", "label": "Metrics Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(gen_ai_application_name)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(gen_ai_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "---\n# ML Pipeline Overserbability\n\nRef: [OpenLIT](https://github.com/openlit/openlit)\n\n---"
   }
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "otel_gpu_fan_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "description": "This panel displays the LLM Request Rate ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(otel_gpu_utilization)", "legendFormat": "Average GPU Utilization" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(otel_gpu_temperature)", "legendFormat": "Average GPU Temperature" }
   ]
  },
  {
   "type": "stat",
   "description": "This panel displays the LLM Request Rate ",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(otel_gpu_power_draw)", "legendFormat": "Average GPU Power Draw" }
   ]
  },
  {
   "type": "stat",
   "description": "This panel displays the LLM Request Rate ",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otel_gpu_memory_used/otel_gpu_memory_available)",
     "legendFormat": "Average GPU Memory Usage"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "otel_gpu_utilization", "legendFormat": "{{gpu_uuid}}-{{gpu_name}}" },
    { "expr": "otel_gpu_dec_utilization", "legendFormat": "{{gpu_uuid}}-{{gpu_name}}" },
    { "expr": "otel_gpu_enc_utilization", "legendFormat": "{{gpu_uuid}}-{{gpu_name}}" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "otel_gpu_temperature", "legendFormat": "{{gpu_uuid}}-{{gpu_name}}" }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "otel_gpu_memory_used", "legendFormat": "Memory Used" },
    { "expr": "otel_gpu_memory_free", "legendFormat": "Memory Free" },
    { "expr": "otel_gpu_memory_total", "legendFormat": "Memory Total" }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "otel_gpu_fan_speed", "legendFormat": "{{gpu_uuid}}-{{gpu_name}}" }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "otel_gpu_power_draw", "legendFormat": "Power Draw" },
    { "expr": "otel_gpu_power_limit", "legendFormat": "Power Limit" }
   ]
  },
  { "title": "Pipeline Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Pipeline Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "otel_duration_milliseconds_sum{service_name=\"my-ml-pipeline\", span_name=\"process_single_frame\"} / otel_duration_milliseconds_count{service_name=\"my-ml-pipeline\", span_name=\"process_single_frame\"}",
     "legendFormat": "{{service_name}}-{{span_name}}"
    }
   ]
  },
  {
   "title": "Model Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "otel_duration_milliseconds_sum{service_name=\"my-ml-pipeline\", span_name=\"person_detection\"} / otel_duration_milliseconds_count{service_name=\"my-ml-pipeline\", span_name=\"person_detection\"}",
     "legendFormat": "{{span_name}}"
    },
    {
     "expr": "otel_duration_milliseconds_sum{service_name=\"my-ml-pipeline\", span_name=\"pose_estimation\"} / otel_duration_milliseconds_count{service_name=\"my-ml-pipeline\", span_name=\"pose_estimation\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Detected People Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "otel_detected_people_count{exported_job=\"my-ml-pipeline\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  }
 ]
}