MODEL_ROOT_DIR := ./data/models/

.PHONY: download
download:
	# huggingface-cli download facebook/sapiens-seg-0.3b-torchscript --local-dir ${MODEL_ROOT_DIR}
	# huggingface-cli download facebook/sapiens-seg-0.6b-torchscript --local-dir ${MODEL_ROOT_DIR}
	huggingface-cli download facebook/sapiens-seg-1b-torchscript --local-dir ${MODEL_ROOT_DIR}

