name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      # Setup environment
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      # Install dependencies and run tests.
      - name: Install Dependencies
        run: poetry install
        shell: bash
      - name: Run Tests
        run: |
          set -o pipefail
          make test | tee pytest-coverage.txt
        shell: bash
      - name: Pytest coverage comment
        if: github.ref != 'refs/heads/main'
        uses: MishaKav/pytest-coverage-comment@v1.1.47
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
